### ISSUE TITLE
bug when trying to send to another local host

### ISSUE THREAD

**Issue by weitaiting** [michellelimxuanli/gaia2#4]
Is the error message here a bug in sender.py? Is this an implementation bug?
I opened two terminals and ran:
`python main.py -me localhost:5000 -them localhost:5001 localhost:5002 `
`python main.py -me localhost:5001 -them localhost:5000 localhost:5002`

None of the 2 nodes received any updates from each other. This is what was printed out:
```
0
Epoch 0 | loss: 0.0075
{'localhost:5000': 0, 'localhost:5002': 0, 'localhost:5001': 1}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/weitaiting/Documents/snlab/gaia2/src/sender.py", line 71, in _actually_run
    self._update_host(host)
  File "/Users/weitaiting/Documents/snlab/gaia2/src/sender.py", line 91, in _update_host
    res = requests.post(host+"/send_update", json={"sender": host, "update": update})
  File "/Users/weitaiting/Documents/snlab/gaia2/venv/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/weitaiting/Documents/snlab/gaia2/venv/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/weitaiting/Documents/snlab/gaia2/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/weitaiting/Documents/snlab/gaia2/venv/lib/python3.7/site-packages/requests/sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "/Users/weitaiting/Documents/snlab/gaia2/venv/lib/python3.7/site-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'localhost:5002/send_update'
```

**Comment by weitaiting** [comment]
This is probably [the cause of the issue](https://stackoverflow.com/questions/15115328/python-requests-no-connection-adapters)
Especially since we have the stack trace above: `host` would probably have just been `localhost:5000` in this line: `requests.post(host+"/send_update", json={"sender": host, "update": update})`

**Comment by michlimlim** [comment]
Yeah I just changed it to "requests.post("http://" + host+"/send_update", json={"sender": host, "update": update})" and the error is gone
